use simplex::constants::DUMMY_SIGNATURE;
use simplex::serde::de::DeserializeOwned;

use simplex_fixtures::artifacts::enum_spend::derived_enum_spend::{Action, EnumSpendArguments, EnumSpendWitness};
use simplex_fixtures::artifacts::nested_sig::derived_nested_sig::{NestedSigArguments, NestedSigWitness};

simplex::include_simf!("../crates/simplex/tests/ui_simfs/enums.simf");

/// Exercises the serde impls generated by `include_simf!`, both the plain
/// typed-map path (no enums in the ABI) and the `UnresolvedValues` path
/// (enums in the ABI, where bare value strings resolve against the
/// program's declared types).
fn assert_serde_roundtrip<T>(value: &T)
where
    T: simplex::serde::Serialize + DeserializeOwned + PartialEq + std::fmt::Debug,
{
    let json = serde_json::to_string(value).expect("serializes");
    let recovered: T = serde_json::from_str(&json).expect("deserializes");
    assert_eq!(*value, recovered, "round-trips through {json}");
}

#[test]
fn enum_witness_serde_roundtrip() {
    for action in [
        Action::Inherit(DUMMY_SIGNATURE),
        Action::Cold(DUMMY_SIGNATURE),
        Action::Hot(DUMMY_SIGNATURE),
    ] {
        assert_serde_roundtrip(&EnumSpendWitness { action });
    }
}

#[test]
fn enum_arguments_serde_roundtrip() {
    use derived_enums::{EnumsArguments, Mode, Wrapper};

    let arguments = EnumsArguments {
        mode: Mode::Pair(7, 42),
        wrapper: Wrapper::Wrapped(Mode::Single(9)),
        ..Default::default()
    };
    assert_serde_roundtrip(&arguments);
}

#[test]
fn non_enum_arguments_in_enum_contract_serde_roundtrip() {
    assert_serde_roundtrip(&EnumSpendArguments { public_key: [0x02; 32] });
}

#[test]
fn non_enum_witness_serde_roundtrip() {
    let witness = NestedSigWitness {
        inherit_or_not: simplex::either::Either::Right(simplex::either::Either::Left(DUMMY_SIGNATURE)),
    };
    assert_serde_roundtrip(&witness);

    let arguments = NestedSigArguments { public_key: [0x02; 32] };
    assert_serde_roundtrip(&arguments);
}
